import { defineConfig, loadEnv } from 'vite';
import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import preact from '@preact/preset-vite';

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  const cfgPath = path.resolve(__dirname, 'web/config.js');

  // During development, generate the config.js file dynamically
  // This allows us to use .env variables without hardcoding them
  if (mode === 'development') {
    mkdirSync(path.dirname(cfgPath), { recursive: true });
    writeFileSync(cfgPath, `
       // Auto-generated by Vite during build (mode: ${mode})
       window.appconfig = {
          dynamicZonesBaseUrl: "${env.DYNAMIC_ZONE_BASE_URL || ''}",
          cloudResourcesBaseUrl: "${env.CLOUD_RESOURCES_BASE_URL || ''}",
          dummyAuth: ${env.DUMMY_AUTH === 'true'},
          "oidc": {
            "client_id": "${env.OIDC_CLIENT_ID}",
            "issuer_url": "${env.OIDC_ISSUER_URL}",
          }
       };
       `
    );
  }

  return {
    root: 'web',
    plugins: [
      preact({
        babel: {
          plugins: mode === 'development'
            ? ['@babel/plugin-transform-react-jsx-source']
            : [],
        },
      }),
    ],
    resolve: {
      alias: {
        react: 'preact/compat',
        'react-dom': 'preact/compat',
        'react-dom/test-utils': 'preact/test-utils',
        'react/jsx-runtime': 'preact/jsx-runtime',
      }
    },
    build: {
      outDir: '../dist',
      emptyOutDir: true,
    },
    server: {
      port: 8084
    },
    define: {
      __APP_VERSION__: JSON.stringify(process.env.npm_package_version),
    },
    clearScreen: true
  };
});
