import { defineConfig, loadEnv } from 'vite';
import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import react from '@vitejs/plugin-react';

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  const cfgPath = path.resolve(__dirname, 'web/config.js');

  // During development, generate the config.js file dynamically
  // This allows us to use .env variables without hardcoding them
  if (mode === 'development') {
    mkdirSync(path.dirname(cfgPath), { recursive: true });
    writeFileSync(cfgPath, `
       // Auto-generated by Vite during build (mode: ${mode})
       window.appconfig = {
          dynamicZonesBaseUrl: "${env.DYNAMIC_ZONE_BASE_URL || ''}",
          cloudResourcesBaseUrl: "${env.CLOUD_RESOURCES_BASE_URL || ''}",
          acmeServer: "${env.ACME_SERVER || 'https://certificates.dhbw.cloud'}",
          dummyAuth: ${env.DUMMY_AUTH === 'true'},
          "oidc": {
            "client_id": "${env.OIDC_CLIENT_ID}",
            "issuer_url": "${env.OIDC_ISSUER_URL}",
          }
       };
       `
    );
  }

  return {
    root: 'web',
    // Source files are .jsx, handled natively by @vitejs/plugin-react
    // (automatic JSX runtime + React Fast Refresh in dev).
    plugins: [react()],
    build: {
      outDir: '../dist',
      emptyOutDir: true,
      rollupOptions: {
        output: {
          // Split large vendors into their own long-lived cacheable chunks
          // (swagger-ui is dynamically imported, so it already lands in its own
          // async chunk and is intentionally not listed here).
          manualChunks: {
            mantine: ['@mantine/core', '@mantine/dates', '@mantine/form', '@mantine/modals', '@mantine/hooks'],
            vendor: ['react', 'react-dom', 'wouter', 'oidc-client-ts'],
          },
        },
      },
    },
    server: {
      port: 8084
    },
    define: {
      __APP_VERSION__: JSON.stringify(process.env.npm_package_version),
    },
    clearScreen: true
  };
});
