// vite.config.js
import { defineConfig, loadEnv } from 'vite';
import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  const cfgPath = path.resolve(__dirname, 'web/config.js');

  mkdirSync(path.dirname(cfgPath), { recursive: true });
  writeFileSync(cfgPath, `
     // Auto-generated by Vite during build (mode: ${mode})
     // Overwrite this file, e.g., using a configmap during deployment in k8s
     window.appconfig = {
        dynamicZonesBaseUrl: "${env.DYNAMIC_ZONE_BASE_URL || ''}",
        appVersion: "${env.npm_package_version}",
     };
     `
  );

  return {
    root: 'web',
    build: {
      outDir: 'dist',
      emptyOutDir: true
    },
    server: {
      port: 8084
    },
    clearScreen: true
  };
});
